name: FYP Local
schema: 'https://schema.getpostman.com/json/collection/v2.1.0/environment.json'
values:
  - key: baseUrl
    value: 'http://localhost:3000'
    type: default
    enabled: true
  - key: testEmail
    value: 'testlead.1780772226351@testcompany.com'
    type: default
    enabled: true
  - key: createdLeadId
    value: ''
    type: default
    enabled: true
  - key: createdTeamId
    value: ''
    type: default
    enabled: true










