name: FYP Local
schema: 'https://schema.getpostman.com/json/collection/v2.1.0/environment.json'
values:
  - key: baseUrl
    value: 'http://localhost:3000'
    type: default
    enabled: true
  - key: testEmail
    value: 'testlead.1781525610059@testcompany.com'
    type: default
    enabled: true
  - key: authToken
    value: ''
    type: secret
    enabled: true
  - key: repLoginEmail
    value: 'daniel.lee@dell.com'
    type: default
    enabled: true
  - key: repLoginPassword
    value: 'rep456'
    type: secret
    enabled: true
  - key: repToken
    value: ''
    type: secret
    enabled: true
  - key: managerEmail
    value: 'james.lim@dell.com'
    type: default
    enabled: true
  - key: managerPassword
    value: 'manager123'
    type: secret
    enabled: true
  - key: managerToken
    value: ''
    type: secret
    enabled: true
  - key: adminEmail
    value: 'sarah.tan@dell.com'
    type: default
    enabled: true
  - key: adminPassword
    value: 'admin123'
    type: secret
    enabled: true
  - key: adminToken
    value: ''
    type: secret
    enabled: true
  - key: userRole
    value: ''
    type: default
    enabled: true
  - key: createdLeadId
    value: ''
    type: default
    enabled: true
  - key: createdTeamId
    value: ''
    type: default
    enabled: true
  - key: createdUserId
    value: ''
    type: default
    enabled: true
  - key: repEmail
    value: ''
    type: default
    enabled: true

