version: "3.8"
services:
  app:
    build: .
    ports:
      - "3000:3000"   # Express
      - "19006:19006" # Expo web
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=example
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: delllead
    ports:
      - "3306:3306"
