name: Backend CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Start backend server
        working-directory: ./backend
        run: node app.js &
      
      - name: Wait for server to start
        run: sleep 10

      - name: Run Postman tests
        shell: pwsh
        working-directory: ./backend
        run: .\scripts\run-tests.ps1

      - name: Stop server
        run: pkill node
